# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zeld2reg.ui'
#
# Created: Sat Aug 22 12:41:27 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_zeld2_reg(QtGui.QMainWindow):

    def __init__(self):
        super(Ui_zeld2_reg, self).__init__()
        self.setupUi(self)


    def setupUi(self, zeld2_reg):
        zeld2_reg.setObjectName("zeld2_reg")
        zeld2_reg.resize(679, 599)
        zeld2_reg.setMinimumSize(QtCore.QSize(679, 599))
        zeld2_reg.setMaximumSize(QtCore.QSize(679, 599))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/img/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        zeld2_reg.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(zeld2_reg)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 611, 481))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.names_box = QtGui.QLineEdit(self.groupBox)
        self.names_box.setGeometry(QtCore.QRect(170, 50, 401, 31))
        self.names_box.setObjectName("names_box")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.email_box = QtGui.QLineEdit(self.groupBox)
        self.email_box.setGeometry(QtCore.QRect(170, 110, 401, 31))
        self.email_box.setObjectName("email_box")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pwd_box = QtGui.QLineEdit(self.groupBox)
        self.pwd_box.setGeometry(QtCore.QRect(170, 170, 401, 31))
        self.pwd_box.setEchoMode(QtGui.QLineEdit.Password)
        self.pwd_box.setObjectName("pwd_box")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pwd2_box = QtGui.QLineEdit(self.groupBox)
        self.pwd2_box.setGeometry(QtCore.QRect(170, 230, 401, 31))
        self.pwd2_box.setEchoMode(QtGui.QLineEdit.Password)
        self.pwd2_box.setObjectName("pwd2_box")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(60, 300, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_6.setOpenExternalLinks(True)
        self.reg_btn = QtGui.QPushButton(self.groupBox)
        self.reg_btn.setGeometry(QtCore.QRect(180, 380, 111, 31))
        self.reg_btn.setObjectName("reg_btn")
        zeld2_reg.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(zeld2_reg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 21))
        self.menubar.setObjectName("menubar")
        zeld2_reg.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(zeld2_reg)
        self.statusbar.setObjectName("statusbar")
        zeld2_reg.setStatusBar(self.statusbar)

        self.retranslateUi(zeld2_reg)
        QtCore.QMetaObject.connectSlotsByName(zeld2_reg)

    def retranslateUi(self, zeld2_reg):
        zeld2_reg.setWindowTitle(QtGui.QApplication.translate("zeld2_reg", "Welcome to ZelDrive!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("zeld2_reg", "Welcome", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("zeld2_reg", "Names :", None, QtGui.QApplication.UnicodeUTF8))
        self.names_box.setPlaceholderText(QtGui.QApplication.translate("zeld2_reg", "Enter your names", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("zeld2_reg", "Email :", None, QtGui.QApplication.UnicodeUTF8))
        self.email_box.setPlaceholderText(QtGui.QApplication.translate("zeld2_reg", "Enter your email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("zeld2_reg", "Password :", None, QtGui.QApplication.UnicodeUTF8))
        self.pwd_box.setPlaceholderText(QtGui.QApplication.translate("zeld2_reg", "Enter your password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("zeld2_reg", "Confirm Password :", None, QtGui.QApplication.UnicodeUTF8))
        self.pwd2_box.setPlaceholderText(QtGui.QApplication.translate("zeld2_reg", "Confirm your password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("zeld2_reg", "<html><head/><body><p>By clicking <span style=\" font-style:italic;\">Register</span>, you confirm that you agree with the <a href=\"http://localhost\"><span style=\" text-decoration: underline; color:#0000ff;\">Terms and Conditions of ZelDrive</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reg_btn.setText(QtGui.QApplication.translate("zeld2_reg", "Register", None, QtGui.QApplication.UnicodeUTF8))

