# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zeld2.ui'
#
# Created: Sat Aug 22 12:38:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import zeld2reg

class Ui_ZelDrive(QtGui.QMainWindow):

    def __init__(self):
        super(Ui_ZelDrive, self).__init__()
        self.setupUi(self)

    def setupUi(self, ZelDrive):
        ZelDrive.setObjectName("ZelDrive")
        ZelDrive.resize(801, 600)
        QtGui.QApplication.setStyle(QtGui.QStyleFactory.create('Cleanlooks'))
        ZelDrive.setMinimumSize(QtCore.QSize(801, 600))
        ZelDrive.setMaximumSize(QtCore.QSize(801, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/img/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ZelDrive.setWindowIcon(icon)
        ZelDrive.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(ZelDrive)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 581, 221))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_total_space = QtGui.QLabel(self.groupBox)
        self.lbl_total_space.setGeometry(QtCore.QRect(140, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_total_space.setFont(font)
        self.lbl_total_space.setObjectName("lbl_total_space")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_used_space = QtGui.QLabel(self.groupBox)
        self.lbl_used_space.setGeometry(QtCore.QRect(140, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_used_space.setFont(font)
        self.lbl_used_space.setObjectName("lbl_used_space")
        self.lbl_free_space = QtGui.QLabel(self.groupBox)
        self.lbl_free_space.setGeometry(QtCore.QRect(140, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_free_space.setFont(font)
        self.lbl_free_space.setObjectName("lbl_free_space")
        self.progressBar = QtGui.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(20, 170, 451, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 310, 581, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lbl_total_cache = QtGui.QLabel(self.groupBox_2)
        self.lbl_total_cache.setGeometry(QtCore.QRect(140, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_total_cache.setFont(font)
        self.lbl_total_cache.setObjectName("lbl_total_cache")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lbl_used_cache = QtGui.QLabel(self.groupBox_2)
        self.lbl_used_cache.setGeometry(QtCore.QRect(140, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_used_cache.setFont(font)
        self.lbl_used_cache.setObjectName("lbl_used_cache")
        self.lbl_free_cache = QtGui.QLabel(self.groupBox_2)
        self.lbl_free_cache.setGeometry(QtCore.QRect(140, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lbl_free_cache.setFont(font)
        self.lbl_free_cache.setObjectName("lbl_free_cache")
        self.progressBar_2 = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 170, 451, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 20, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(630, 60, 151, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.start_drive_btn = QtGui.QPushButton(self.groupBox_3)
        self.start_drive_btn.setEnabled(False)
        self.start_drive_btn.setGeometry(QtCore.QRect(10, 30, 91, 23))
        self.start_drive_btn.setObjectName("start_drive_btn")
        self.stop_drive_btn = QtGui.QPushButton(self.groupBox_3)
        self.stop_drive_btn.setGeometry(QtCore.QRect(10, 70, 91, 23))
        self.stop_drive_btn.setObjectName("stop_drive_btn")
        self.restart_drive_btn = QtGui.QPushButton(self.groupBox_3)
        self.restart_drive_btn.setGeometry(QtCore.QRect(10, 110, 91, 23))
        self.restart_drive_btn.setObjectName("restart_drive_btn")
        ZelDrive.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ZelDrive)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuMore = QtGui.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        ZelDrive.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ZelDrive)
        self.statusbar.setObjectName("statusbar")
        ZelDrive.setStatusBar(self.statusbar)
        self.actionWhat_s_ZelDrive = QtGui.QAction(ZelDrive)
        self.actionWhat_s_ZelDrive.setObjectName("actionWhat_s_ZelDrive")
        self.actionPurchase_Space = QtGui.QAction(ZelDrive)
        self.actionPurchase_Space.setObjectName("actionPurchase_Space")
        self.actionCheck_for_updates = QtGui.QAction(ZelDrive)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.actionFAQs = QtGui.QAction(ZelDrive)
        self.actionFAQs.setObjectName("actionFAQs")
        self.actionTerms_and_Conditions = QtGui.QAction(ZelDrive)
        self.actionTerms_and_Conditions.setObjectName("actionTerms_and_Conditions")
        self.actionAbout_ZelDrive = QtGui.QAction(ZelDrive)
        self.actionAbout_ZelDrive.setObjectName("actionAbout_ZelDrive")
        self.actionRegister = QtGui.QAction(ZelDrive)
        self.actionRegister.setObjectName("actionRegister")
        self.actionImport_drive = QtGui.QAction(ZelDrive)
        self.actionImport_drive.setObjectName("actionImport_drive")
        self.actionSettings = QtGui.QAction(ZelDrive)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtGui.QAction(ZelDrive)
        self.actionExit.setObjectName("actionExit")
        self.menuSettings.addAction(self.actionRegister)
        self.menuSettings.addAction(self.actionImport_drive)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionExit)
        self.menuMore.addAction(self.actionWhat_s_ZelDrive)
        self.menuMore.addAction(self.actionPurchase_Space)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionFAQs)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionTerms_and_Conditions)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionAbout_ZelDrive)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(ZelDrive)
        QtCore.QMetaObject.connectSlotsByName(ZelDrive)

        self.actionRegister.triggered.connect(self.launch_reg)
        self.actionImport_drive.triggered.connect(self.launch_imp_d)
        self.actionSettings.triggered.connect(self.launch_set)
        self.actionExit.triggered.connect(self.goodbye)

    def retranslateUi(self, ZelDrive):
        ZelDrive.setWindowTitle(QtGui.QApplication.translate("ZelDrive", "ZelDrive Control", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ZelDrive", "Disk Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ZelDrive", "Total Space  :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_total_space.setText(QtGui.QApplication.translate("ZelDrive", "40 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ZelDrive", "Used Space :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ZelDrive", "Free Space  :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_used_space.setText(QtGui.QApplication.translate("ZelDrive", "0 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_free_space.setText(QtGui.QApplication.translate("ZelDrive", "40 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ZelDrive", "Cache Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ZelDrive", "Total Cache  :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_total_cache.setText(QtGui.QApplication.translate("ZelDrive", "2 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ZelDrive", "Used Cache :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ZelDrive", "Free Cache  :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_used_cache.setText(QtGui.QApplication.translate("ZelDrive", "0 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_free_cache.setText(QtGui.QApplication.translate("ZelDrive", "2 GB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ZelDrive", "Reload Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setShortcut(QtGui.QApplication.translate("ZelDrive", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ZelDrive", "Action Box", None, QtGui.QApplication.UnicodeUTF8))
        self.start_drive_btn.setText(QtGui.QApplication.translate("ZelDrive", "Start ZelDrive", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_drive_btn.setText(QtGui.QApplication.translate("ZelDrive", "Stop ZelDrive", None, QtGui.QApplication.UnicodeUTF8))
        self.restart_drive_btn.setText(QtGui.QApplication.translate("ZelDrive", "Restart ZelDrive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("ZelDrive", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMore.setTitle(QtGui.QApplication.translate("ZelDrive", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhat_s_ZelDrive.setText(QtGui.QApplication.translate("ZelDrive", "What\'s ZelDrive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhat_s_ZelDrive.setShortcut(QtGui.QApplication.translate("ZelDrive", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Space.setText(QtGui.QApplication.translate("ZelDrive", "Purchase Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Space.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_updates.setText(QtGui.QApplication.translate("ZelDrive", "Check for updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_updates.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFAQs.setText(QtGui.QApplication.translate("ZelDrive", "FAQs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFAQs.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTerms_and_Conditions.setText(QtGui.QApplication.translate("ZelDrive", "Terms and Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTerms_and_Conditions.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_ZelDrive.setText(QtGui.QApplication.translate("ZelDrive", "About ZelDrive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_ZelDrive.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegister.setText(QtGui.QApplication.translate("ZelDrive", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegister.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_drive.setText(QtGui.QApplication.translate("ZelDrive", "Import drive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_drive.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("ZelDrive", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("ZelDrive", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("ZelDrive", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

    def launch_reg(self):
        self.reg = zeld2reg.Ui_zeld2_reg()
        self.reg.show()

    def launch_imp_d(self):
        import zeld2_imp_d
        self.imp_d = zeld2_imp_d.Ui_zeld2_imp_d()
        self.imp_d.show()

    def launch_set(self):
        import zeld2_set
        self.zset = zeld2_set.Ui_zeld2_set()
        self.zset.show()

    def goodbye(self):
        self.close()


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    obj = Ui_ZelDrive()
    obj.show()
    sys.exit(app.exec_())
